# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8f3688962dbcefe674fc10ff2eb06d9c1e70117483521a21c6867755834a23cf1c863bce1cf7f9585d4cd57c5876d174117fcb4eb9c09bd108d833e8d81572

test:
  secret_key_base: b8c998ed4beab56ce40ec6b3b8041ec6fe04bef06cf21bc026bc5109eb34d7c7e32d29323c888b3f981c831ec36321a1f111ac8116cfb528c9a6b2f3ab7db13e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
